version: "3"
services:
  postgres:
    container_name: postgresDB
    image: postgres:11.5
    ports:
      - "5433:5432"
    volumes:
      - postgresdata:/data/postgres
      - postgresdbdata:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadminTool
    image: dpage/pgadmin4
    ports:
      - "9091:80"
    volumes:
      - pgadmindata:/root/.pgadmin
      - pgadminlibdata:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

volumes:
  postgresdata:
    driver: local
  postgresdbdata:
    driver: local
  pgadmindata:
    driver: local
  pgadminlibdata:
    driver: local

networks:
  postgres:
    driver: bridge

